### ISSUE TITLE
Doesn't support required array fields

### ISSUE THREAD

**Issue by OmgImAlexis** [jarnojellesma/graphql-to-json-converter#3]
`"]type": {` is the main line I have the issue with. I'm guessing something is broken in the parsing but since the parsing file has almost no comments it's really hard to debug.

```graphql
type Query {
	user: User
	users: [Users]
	message: Message
	messages: [Message!]
}
```

```shell
➜  graphql-to-json-converter git:(master) npm test          

> graphql-to-json-converter@1.2.0 test /Users/xo/code/graphql-to-json-converter
> mocha test/ --recursive --exit



  Converter
    1) works


  0 passing (29ms)
  1 failing

  1) Converter
       works:

      AssertionError: expected { Object (type, input, ...) } to deeply equal { Object (type, input, ...) }
      + expected - actual

               "required": false
               "type": "User"
             }
           }
      -    "Query": {
      -      "]type": {
      -        "Mutation": {
      -          "createMessage": {
      -            "args": {
      -              "text": {
      -                "array": false
      -                "required": false
      -                "type": "String"
      -              }
      -            }
      +    "Mutation": {
      +      "createMessage": {
      +        "args": {
      +          "text": {
                   "array": false
                   "required": false
      -            "type": "Message"
      +            "type": "String"
                 }
      -          "createUser": {
      -            "args": {
      -              "data": {
      -                "array": false
      -                "required": true
      -                "type": "UserInput"
      -              }
      -            }
      +        }
      +        "array": false
      +        "required": false
      +        "type": "Message"
      +      }
      +      "createUser": {
      +        "args": {
      +          "data": {
                   "array": false
      -            "required": false
      -            "type": "User"
      +            "required": true
      +            "type": "UserInput"
                 }
      -          "uploadPhotos": {
      -            "args": {
      -              "data": {
      -                "array": true
      -                "required": false
      -                "type": "PhotoInput,"
      -              }
      -              "repository": {
      -                "array": false
      -                "required": false
      -                "type": "ID,"
      -              }
      -            }
      +        }
      +        "array": false
      +        "required": false
      +        "type": "User"
      +      }
      +      "uploadPhotos": {
      +        "args": {
      +          "data": {
                   "array": true
                   "required": false
      -            "type": "Photo"
      +            "type": "PhotoInput,"
                 }
      +          "repository": {
      +            "array": false
      +            "required": false
      +            "type": "ID,"
      +          }
               }
      +        "array": true
      +        "required": false
      +        "type": "Photo"
             }
      +    }
      +    "Query": {
             "message": {
               "array": false
               "required": false
               "type": "Message"
             }
             "messages": {
               "array": true
      -        "required": true
      +        "required": false
               "type": "Message"
             }
             "user": {
               "array": false
      
      at Context.<anonymous> (test/converter.spec.js:10:24)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
```

PING: @jarnojellesma

**Comment by jarnojellesma** [comment]
Hi Alexis,

Unfortunately it has been a long time since I've been working on this
project. Besides I'm not working with graphql anymore. Please feel free to
make a pull request for any changes required.

Have a nice day.

Jarno
